src/components/VariablePanel/VariablePanel.test.tsx
src/components/VariablePanel/VariablePanel.tsx
src/types/variable.ts

1. Improve Select All.
2. Improve Types.
3. Improve values not defined in the URL.
4. Refactor Data Table logic.

Improve Legacy Code

---

CHANGELOG.md
package-lock.json
package.json
src/components/Table/Table.styles.tsx
src/components/Table/Table.tsx
src/components/Table/index.ts
src/components/VariablePanel/VariablePanel.tsx
src/components/VariablePanel/useRuntimeVariable.ts
src/components/VariablePanel/useTable.tsx
src/styles.ts

* Add runtime variable checker
* Add table scroll

Add react-table v8 instead of Table

---

CHANGELOG.md
src/components/VariablePanel/VariablePanel.tsx
src/components/VariablePanel/useTable.tsx
src/module.test.ts
src/module.ts
src/types/panel.ts

1. Add Field Picker for Variable values.
2. Add Field Picker for Status values.
3. Refactoring.

Add Field options for variable values and statuses

---

CHANGELOG.md
provisioning/dashboards/home.json
src/components/Table/Table.test.tsx
src/components/Table/Table.tsx
src/components/VariablePanel/VariablePanel.tsx
src/constants/index.ts
src/constants/panel.ts
src/constants/tests.ts
src/module.test.ts
src/module.ts
src/types/panel.ts

Add Display Header option

---

CHANGELOG.md
src/components/Table/Table.tsx
src/components/VariablePanel/useTable.test.tsx
src/components/VariablePanel/useTable.tsx
src/constants/tests.ts
src/styles.ts

Add the ability to collapse parent rows

---

CHANGELOG.md
provisioning/dashboards/home.json
src/components/VariablePanel/VariablePanel.tsx
src/components/VariablePanel/useContentPosition.ts
src/constants/panel.ts
src/module.ts
src/styles.ts
src/types/panel.ts

Add a Sticky option to follow when scrolling.

Add a Sticky option to follow when scrolling

---

CHANGELOG.md
README.md
package.json
src/components/Table/Filter.tsx
src/components/Table/Table.test.tsx
src/components/Table/Table.tsx
src/components/Table/styles.ts
src/components/VariablePanel/useTable.tsx
src/components/VariablePanel/utils.test.ts
src/components/VariablePanel/utils.ts
src/constants/panel.ts
src/constants/tests.ts
src/module.test.ts
src/module.ts
src/types/panel.ts

Add Table Filter

---

CHANGELOG.md
src/components/VariablePanel/useFavorites.test.ts
src/components/VariablePanel/useFavorites.ts
src/components/VariablePanel/useTable.test.tsx
src/components/VariablePanel/useTable.tsx
src/components/VariablePanel/utils.ts
src/constants/panel.ts
src/constants/tests.ts
src/module.ts
src/styles.ts
src/types/panel.ts
src/types/table.ts

Add a favorites list for devices.

Add favorites list for devices

---

CHANGELOG.md
src/components/FieldsEditor/FieldsEditor.test.tsx
src/components/FieldsEditor/FieldsEditor.tsx

New levels should be added to the end of the list.

Update adding new Level to last

---

src/components/VariablePanel/VariablePanel.test.tsx
src/components/VariablePanel/useTable.test.tsx
src/components/VariablePanel/utils.test.ts
src/components/VariablePanel/utils.ts

Hide unselectable items

---

src/components/Table/Filter.tsx
src/components/VariablePanel/VariablePanel.test.tsx
src/components/VariablePanel/useTable.test.tsx
src/components/VariablePanel/useTable.tsx
src/components/VariablePanel/utils.test.ts
src/components/VariablePanel/utils.ts
src/styles.ts
src/types/table.ts

Add Favorite icon to filter selected favorites.

Add a Favorite icon to filter selected favorites

---

.eslintrc
CHANGELOG.md
src/components/Table/Filter.tsx
src/components/VariablePanel/useRuntimeVariables.ts
src/components/VariablePanel/useTable.test.tsx
src/components/VariablePanel/useTable.tsx
src/components/VariablePanel/utils.ts
src/constants/panel.ts
src/module.ts
src/types/panel.ts
src/types/table.ts

Add option to display variable name in front of the value

---

CHANGELOG.md
src/components/VariablePanel/VariablePanel.tsx
src/constants/panel.ts
src/hooks/index.ts
src/hooks/useRuntimeVariables.ts
src/hooks/useScrollToSelected.test.tsx
src/hooks/useScrollToSelected.ts
src/hooks/useTable.tsx
src/module.ts
src/types/panel.ts

Add auto scroll to the selected variable

---

CHANGELOG.md
README.md
package.json

Community signed release

---

CHANGELOG.md
package.json
provisioning/dashboards/home.json
src/hooks/useTable.test.tsx
src/hooks/useTable.tsx

Update single select variable with All enabled

---

CHANGELOG.md
provisioning/dashboards/home.json
provisioning/dashboards/panels.json
src/hooks/useTable.tsx
src/module.ts

Allow sorting groups

---

provisioning/dashboards/panels.json
src/components/TableView/TableView.test.tsx
src/hooks/useTable.test.tsx
src/hooks/useTable.tsx
src/types/table.ts
src/utils/table.test.ts
src/utils/table.ts

Resolves #56 
When a Variable has keys and values, the Table should use values like minimized view.

Fix variables with text and value in Table/Tree View

---

CHANGELOG.md
package.json
src/components/ButtonView/ButtonView.test.tsx
src/components/ButtonView/ButtonView.tsx
src/components/ButtonView/index.ts
src/components/ButtonView/styles.ts
src/components/VariablePanel/VariablePanel.test.tsx
src/components/VariablePanel/VariablePanel.tsx
src/constants/panel.ts
src/constants/tests.ts
src/hooks/index.ts
src/hooks/useStatus.test.ts
src/hooks/useStatus.ts
src/hooks/useTable.tsx
src/module.test.ts
src/module.ts
src/types/index.ts
src/types/panel.ts
src/types/status.ts
src/utils/table.ts

Resolves #45 
Light theme:
Dark theme:

Add Button View

---

src/components/ButtonView/ButtonView.test.tsx
src/components/ButtonView/ButtonView.tsx
src/constants/panel.ts
src/constants/tests.ts
src/hooks/useTable.test.tsx
src/hooks/useTable.tsx
src/module.ts
src/types/panel.ts
src/utils/table.test.ts
src/utils/table.ts

Allow group selection

---

CHANGELOG.md
src/components/TextVariable/TextVariable.test.tsx
src/components/TextVariable/TextVariable.tsx

Add handling pressing enter and escape keys for Text Variable

---

CHANGELOG.md
src/components/Collapse/styles.ts
src/components/GroupsEditor/GroupsEditor.test.tsx
src/components/GroupsEditor/GroupsEditor.tsx
src/components/GroupsEditor/styles.ts
src/constants/tests.ts

Resolves #79 
Editting state
Invalid name state

Add Group rename functionality

---

CHANGELOG.md
src/components/TableView/styles.ts
src/hooks/useTable.test.tsx
src/hooks/useTable.tsx

Add toggle expanded row state by clicking on label

---

CHANGELOG.md
src/utils/variable.test.ts
src/utils/variable.ts

Add the deselection of All variable value which is not defined in the URL

---

CHANGELOG.md
src/hooks/useTable.test.tsx
src/utils/table.ts

Removing as not planned and missed when tested.
Resolves #76

Removed ability to add group to favorites

---

CHANGELOG.md
src/components/TableView/TableView.test.tsx
src/components/TableView/TableView.tsx
src/constants/panel.ts
src/hooks/index.ts
src/hooks/useLocalStorage.test.ts
src/hooks/useLocalStorage.ts
src/module.ts
src/types/panel.ts

Resolves: #109 
https://www.loom.com/share/03ed17bc98de4bbb8facf11f6601f6af

Added saved selected group option

---

CHANGELOG.md
src/components/ButtonView/ButtonView.styles.ts
src/components/ButtonView/ButtonView.tsx
src/components/MinimizeView/MinimizeView.styles.ts
src/components/MinimizeView/MinimizeView.tsx
src/constants/panel.ts
src/module.ts
src/types/panel.ts

Add label for Button view

---

CHANGELOG.md
package.json
src/hooks/useTable.tsx
src/types/table.ts
src/utils/table.test.ts
src/utils/table.ts

Added the indeterminate state to the checkboxes

---

CHANGELOG.md
package-lock.json
src/__mocks__/@grafana/ui.tsx
src/components/MinimizeView/MinimizeView.tsx
src/components/OptionsVariable/OptionsVariable.test.tsx
src/components/OptionsVariable/OptionsVariable.tsx
src/constants/panel.ts
src/module.ts
src/types/panel.ts

Add support new items in Variable (minimize)

---

CHANGELOG.md
src/constants/panel.ts
src/module.ts

Update panel options to make the difference between multi-level selection and preserve group selection.

Update Multi Level option

---

test/panel.spec.ts

Added `maxDiffPixelRatio: 0.1`.

Update E2E screenshot comparison

---

README.md
src/hooks/useStatus.ts
src/plugin.json
src/utils/table.ts

Resolves: #142 
Remove warnings:
`get`  
`toArray()`

Prepare for Grafana 11

---

CHANGELOG.md
src/components/ButtonView/ButtonView.tsx

Add scrollbar for button view 

---

CHANGELOG.md
package.json
src/components/TableView/TableView.tsx
src/constants/panel.ts
src/module.ts
src/types/panel.ts
src/utils/test.ts

Add panel options for changing tabs order

---

CHANGELOG.md
package-lock.json
package.json
src/constants/panel.ts
src/hooks/useFavorites.ts
src/migration.test.ts
src/migration.ts
src/module.ts
src/types/panel.ts

Update the local storage key for favorites

---

CHANGELOG.md
package.json
src/components/OptionsVariable/OptionsVariable.test.tsx
src/components/OptionsVariable/OptionsVariable.tsx

Update select variable on Minimize view

---

CHANGELOG.md
package.json
provisioning/dashboards/panels.json
src/components/Table/Table.test.tsx
src/components/Table/Table.tsx
src/components/TableView/TableView.tsx
src/hooks/useTable.tsx

Update behavior in table view for Textbox variable type

---

CHANGELOG.md
LICENSE
package-lock.json
src/components/Table/Table.test.tsx
src/hooks/useTable.test.tsx
src/hooks/useTable.tsx

Update display favorites icon

---

CHANGELOG.md
src/components/ButtonView/ButtonView.tsx
src/components/MinimizeView/MinimizeView.tsx
src/components/SliderView/SliderView.tsx
src/components/TableView/TableView.tsx
src/module.ts

Add not supports variable type Alert message

---

.github/workflows/release.yml
CHANGELOG.md
README.md
package.json

Updated release workflow to include attestation

---

CHANGELOG.md
package-lock.json
package.json

Part of: [business-packages-80](https://github.com/VolkovLabs/business-packages/issues/80)

Remove @volkovlabs/grafana-utils

---

CHANGELOG.md
provisioning/dashboards/expand-collapse.json
src/components/TableView/TableView.tsx
src/hooks/useContentPosition.test.tsx
src/hooks/useContentPosition.ts
src/types/panel.ts

Add resize behavior for panel with 'Sticky' header

---

CHANGELOG.md
package.json
provisioning/dashboards/alerts.json
src/components/ButtonView/ButtonView.tsx
src/components/GroupsEditor/GroupsEditor.styles.ts
src/components/GroupsEditor/GroupsEditor.test.tsx
src/components/GroupsEditor/GroupsEditor.tsx
src/components/MinimizeView/MinimizeView.tsx
src/components/SliderView/SliderView.tsx
src/components/TableView/TableView.test.tsx
src/components/TableView/TableView.tsx
src/constants/panel.ts
src/constants/tests.ts
src/hooks/useContentPosition.test.tsx
src/hooks/useTable.tsx
src/module.ts
src/types/panel.ts
src/utils/test.ts

Add a custom message for the 'no data' and 'variable not selected' cases

---

provisioning/dashboards/minimize-table.json
src/__mocks__/@grafana/ui.tsx
src/components/TableView/TableView.styles.ts
src/components/TableView/TableView.test.tsx
src/components/TableView/TableView.tsx
src/components/TableView/components/DrawerTable/DrawerTable.test.tsx
src/components/TableView/components/DrawerTable/DrawerTable.tsx
src/components/TableView/components/DrawerTable/index.ts
src/components/TableView/components/index.ts
src/constants/panel.ts
src/constants/tests.ts
src/hooks/useTable.tsx
src/migration.ts
src/module.ts
src/types/panel.ts
src/utils/test.ts

Resolves: #261 
Warning resolved in [262 PR](https://github.com/VolkovLabs/business-variable/pull/262)

Add minimized view for Tree View layout

---

CHANGELOG.md
package-lock.json
package.json
src/components/TableView/TableView.tsx

Update menu dots layout to prevent overlap

---

CHANGELOG.md
src/hooks/useContentPosition.test.tsx
src/hooks/useContentPosition.ts
src/types/panel.ts

Zendesk ticket: https://volkovlabs.zendesk.com/agent/tickets/193

Update to min Grafana version 11.5.0

---

CHANGELOG.md
src/hooks/useDockMenuPosition.test.tsx
src/hooks/useDockMenuPosition.tsx
src/utils/dock-menu.test.ts
src/utils/dock-menu.ts
src/utils/dom-utils.test.ts
src/utils/dom-utils.ts

Zendesk ticket https://volkovlabs.zendesk.com/agent/tickets/182

Update panel in docked menu on window resize
